Repository apache/maven-clean-plugin, pull requests merged in 2025-01, with the labels that each got.

#68 Add Release Drafter
  .github/release-drafter-3.x.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: enhancement

#69 Add Release Drafter - 3.x
  .github/workflows/release-drafter.yml
Labels: enhancement

#66 Bump Maven in CI to 4.0 rc2
  .github/workflows/maven-verify.yml
Labels: github_actions

#62 [MCLEAN-126] Replaced old File API with new Path equivalent where possible
  src/main/java/org/apache/maven/plugins/clean/CleanMojo.java
  src/main/java/org/apache/maven/plugins/clean/Cleaner.java
  src/test/java/org/apache/maven/plugins/clean/CleanMojoTest.java
  src/test/java/org/apache/maven/plugins/clean/CleanerTest.java
Labels: enhancement

#65 [MCLEAN-127] Use Files.createSymbolicLink instead of shelling out
  src/it/dangling-symlinks/setup.groovy
  src/it/dangling-symlinks/verify.groovy
  src/it/symlink-dont-follow/setup.groovy
  src/it/symlink-dont-follow/verify.groovy
  src/test/java/org/apache/maven/plugins/clean/Utils.java
Labels: enhancement

#71 Bump maven-site-plugin to 3.21.0 and Skin to 2.0.1
  pom.xml
Labels: maintenance

#79 Add PR Automation
  .github/workflows/pr-automation.yml
Labels: enhancement

#80 Add PR Automation
  .github/workflows/pr-automation.yml
Labels: enhancement

#81 Use resolved versions in release drafter
  .github/release-drafter-3.x.yml
  .github/release-drafter.yml
Labels: enhancement

#82 Use COMPLETE for version-template in release drafter
  .github/release-drafter.yml
Labels: enhancement

#83 Fix license/notice
  LICENSE
  NOTICE
Labels: maintenance
